### ISSUE TITLE
Frontend TODO

### ISSUE THREAD

**Issue by holic** [holic/ethfs#2]
- [x] file uploader
  - [x] split into chunks
  - [x] optionally base64 encode
  - [x] optionally compress (fflate compatible)
  - [x] emit metadata (e.g. content type)
  - [ ] allow file renames, encourage namespacing
- [x] file explorer
  - [x] set up indexer
  - [x] parse metadata
  - [ ] allow folders?
  - [x] file search
- [x] file viewer
  - [x] preview file contents
  - [x] code snippets for using in solidity
- [ ] docs

**Comment by holic** [comment]
should metadata be signed by frontend so the indexer can just look for signed metadata and throw out the rest?

**Comment by holic** [comment]
some small details
- [ ] mouse down should trigger focus of a window rather than mouse up
- [ ] file drop hover should trigger focus on upload window
